/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace ImpalaSharp.Thrift.Impala
{
  public enum TImpalaQueryOptions
  {
    ABORT_ON_ERROR = 0,
    MAX_ERRORS = 1,
    DISABLE_CODEGEN = 2,
    BATCH_SIZE = 3,
    MEM_LIMIT = 4,
    NUM_NODES = 5,
    MAX_SCAN_RANGE_LENGTH = 6,
    MAX_IO_BUFFERS = 7,
    NUM_SCANNER_THREADS = 8,
    ALLOW_UNSUPPORTED_FORMATS = 9,
    DEFAULT_ORDER_BY_LIMIT = 10,
    DEBUG_ACTION = 11,
    ABORT_ON_DEFAULT_LIMIT_EXCEEDED = 12,
    PARQUET_COMPRESSION_CODEC = 13,
    HBASE_CACHING = 14,
    HBASE_CACHE_BLOCKS = 15,
    PARQUET_FILE_SIZE = 16,
    EXPLAIN_LEVEL = 17,
    SYNC_DDL = 18,
    YARN_POOL = 19,
    V_CPU_CORES = 20,
    RESERVATION_REQUEST_TIMEOUT = 21,
  }
}
