/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace ImpalaSharp.Thrift.Impala
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class TResetTableReq : TBase
  {

    public string Db_name { get; set; }

    public string Table_name { get; set; }

    public TResetTableReq() {
    }

    public TResetTableReq(string db_name, string table_name) : this() {
      this.Db_name = db_name;
      this.Table_name = table_name;
    }

    public void Read (TProtocol iprot)
    {
      bool isset_db_name = false;
      bool isset_table_name = false;
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              Db_name = iprot.ReadString();
              isset_db_name = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              Table_name = iprot.ReadString();
              isset_table_name = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
      if (!isset_db_name)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
      if (!isset_table_name)
        throw new TProtocolException(TProtocolException.INVALID_DATA);
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("TResetTableReq");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      field.Name = "db_name";
      field.Type = TType.String;
      field.ID = 1;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(Db_name);
      oprot.WriteFieldEnd();
      field.Name = "table_name";
      field.Type = TType.String;
      field.ID = 2;
      oprot.WriteFieldBegin(field);
      oprot.WriteString(Table_name);
      oprot.WriteFieldEnd();
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("TResetTableReq(");
      sb.Append("Db_name: ");
      sb.Append(Db_name);
      sb.Append(",Table_name: ");
      sb.Append(Table_name);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
