/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace ImpalaSharp.Thrift.Impala
{
  public enum TStatusCode
  {
    OK = 0,
    CANCELLED = 1,
    ANALYSIS_ERROR = 2,
    NOT_IMPLEMENTED_ERROR = 3,
    RUNTIME_ERROR = 4,
    MEM_LIMIT_EXCEEDED = 5,
    INTERNAL_ERROR = 6,
  }
}
