/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace ImpalaSharp.Thrift.Beeswax
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Query : TBase
  {
    private string _query_string;
    private List<string> _configuration;
    private string _hadoop_user;

    public string Query_string
    {
      get
      {
        return _query_string;
      }
      set
      {
        __isset.query_string = true;
        this._query_string = value;
      }
    }

    public List<string> Configuration
    {
      get
      {
        return _configuration;
      }
      set
      {
        __isset.configuration = true;
        this._configuration = value;
      }
    }

    public string Hadoop_user
    {
      get
      {
        return _hadoop_user;
      }
      set
      {
        __isset.hadoop_user = true;
        this._hadoop_user = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool query_string;
      public bool configuration;
      public bool hadoop_user;
    }

    public Query() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              Query_string = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.List) {
              {
                Configuration = new List<string>();
                TList _list0 = iprot.ReadListBegin();
                for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                {
                  string _elem2 = null;
                  _elem2 = iprot.ReadString();
                  Configuration.Add(_elem2);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.String) {
              Hadoop_user = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Query");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Query_string != null && __isset.query_string) {
        field.Name = "query_string";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Query_string);
        oprot.WriteFieldEnd();
      }
      if (Configuration != null && __isset.configuration) {
        field.Name = "configuration";
        field.Type = TType.List;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.String, Configuration.Count));
          foreach (string _iter3 in Configuration)
          {
            oprot.WriteString(_iter3);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (Hadoop_user != null && __isset.hadoop_user) {
        field.Name = "hadoop_user";
        field.Type = TType.String;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Hadoop_user);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Query(");
      sb.Append("Query_string: ");
      sb.Append(Query_string);
      sb.Append(",Configuration: ");
      sb.Append(Configuration);
      sb.Append(",Hadoop_user: ");
      sb.Append(Hadoop_user);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
