/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;

namespace ImpalaSharp.Thrift
{
  public static class cli_serviceConstants
  {
    public static THashSet<TTypeId> PRIMITIVE_TYPES = new THashSet<TTypeId>();
    public static THashSet<TTypeId> COMPLEX_TYPES = new THashSet<TTypeId>();
    public static THashSet<TTypeId> COLLECTION_TYPES = new THashSet<TTypeId>();
    public static Dictionary<TTypeId, string> TYPE_NAMES = new Dictionary<TTypeId, string>();
    static cli_serviceConstants()
    {
      PRIMITIVE_TYPES.Add(TTypeId.BOOLEAN_TYPE);
      PRIMITIVE_TYPES.Add(TTypeId.TINYINT_TYPE);
      PRIMITIVE_TYPES.Add(TTypeId.SMALLINT_TYPE);
      PRIMITIVE_TYPES.Add(TTypeId.INT_TYPE);
      PRIMITIVE_TYPES.Add(TTypeId.BIGINT_TYPE);
      PRIMITIVE_TYPES.Add(TTypeId.FLOAT_TYPE);
      PRIMITIVE_TYPES.Add(TTypeId.DOUBLE_TYPE);
      PRIMITIVE_TYPES.Add(TTypeId.STRING_TYPE);
      PRIMITIVE_TYPES.Add(TTypeId.TIMESTAMP_TYPE);
      PRIMITIVE_TYPES.Add(TTypeId.BINARY_TYPE);
      PRIMITIVE_TYPES.Add(TTypeId.DECIMAL_TYPE);
      COMPLEX_TYPES.Add(TTypeId.ARRAY_TYPE);
      COMPLEX_TYPES.Add(TTypeId.MAP_TYPE);
      COMPLEX_TYPES.Add(TTypeId.STRUCT_TYPE);
      COMPLEX_TYPES.Add(TTypeId.UNION_TYPE);
      COMPLEX_TYPES.Add(TTypeId.USER_DEFINED_TYPE);
      COLLECTION_TYPES.Add(TTypeId.ARRAY_TYPE);
      COLLECTION_TYPES.Add(TTypeId.MAP_TYPE);
      TYPE_NAMES[TTypeId.BOOLEAN_TYPE] = "BOOLEAN";
      TYPE_NAMES[TTypeId.TINYINT_TYPE] = "TINYINT";
      TYPE_NAMES[TTypeId.SMALLINT_TYPE] = "SMALLINT";
      TYPE_NAMES[TTypeId.INT_TYPE] = "INT";
      TYPE_NAMES[TTypeId.BIGINT_TYPE] = "BIGINT";
      TYPE_NAMES[TTypeId.FLOAT_TYPE] = "FLOAT";
      TYPE_NAMES[TTypeId.DOUBLE_TYPE] = "DOUBLE";
      TYPE_NAMES[TTypeId.STRING_TYPE] = "STRING";
      TYPE_NAMES[TTypeId.TIMESTAMP_TYPE] = "TIMESTAMP";
      TYPE_NAMES[TTypeId.BINARY_TYPE] = "BINARY";
      TYPE_NAMES[TTypeId.ARRAY_TYPE] = "ARRAY";
      TYPE_NAMES[TTypeId.MAP_TYPE] = "MAP";
      TYPE_NAMES[TTypeId.STRUCT_TYPE] = "STRUCT";
      TYPE_NAMES[TTypeId.UNION_TYPE] = "UNIONTYPE";
      TYPE_NAMES[TTypeId.DECIMAL_TYPE] = "DECIMAL";
    }
  }
}
