/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace ImpalaSharp.Thrift
{
  public enum TProtocolVersion
  {
    HIVE_CLI_SERVICE_PROTOCOL_V1 = 0,
  }
}
